name: Generate Dev Container Cache Image

on:
  push:
    # Update this to build images for other branches
    branch:
      - 'main'

    # Update this list of there are other files you want to watch to do cache updates
    paths:
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'

jobs:
  devcontainer:
    name: Generate cache image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build and push cache image
        id: build_and_push
        run: |
          set -e
          CONTAINER_IMAGE_REGISTRY=ghcr.io
          REPOSITORY_PATH=codespaces-contrib/demo/dependency-caching
          IMAGE_ID="${CONTAINER_IMAGE_REGISTRY}/${REPOSITORY_PATH}" 

          GIT_BRANCH=$(echo "${{ github.ref }}" | grep -oP 'refs/(heads|tags)/\K(.+)')
          if [ "$GIT_BRANCH" == "" ]; then GIT_BRANCH=master; fi
          echo "${{ secrets.GHCR_PAT }}" | docker login "${CONTAINER_IMAGE_REGISTRY}" -u "${{ secrets.GHCR_USER }}" --password-stdin 
          .devcontainer/cache/build-cache-image.sh "${IMAGE_ID}" "${IMAGE_ID}" "${GIT_BRANCH}" "node"

