name: Generate Dev Container Cache Image

on:
  push:
    # Update this to build images for other branches
    branch:
      - 'devcontainer-test'
      - 'main'

    # Update this list of there are other files you want to watch to do cache updates
    paths:
      - '**/package-lock.json'
      - '**/yarn.lock'

jobs:
  devcontainer:
    name: Generate cache image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Build and push cache image
        id: build_and_push
        run: |
          set -e
          CONTAINER_IMAGE_REGISTRY=ghcr.io
          REPOSITORY_PATH=codespaces-contrib/demo/dependency-caching
          BRANCH_TAG="base-clantz-sample-wip"
          BASE_IMAGE_ID="${CONTAINER_IMAGE_REGISTRY}/${REPOSITORY_PATH}:${BRANCH_TAG}"

          echo "${{ secrets.GHCR_PAT }}" | docker login "${CONTAINER_IMAGE_REGISTRY}" -u "${{ secrets.GHCR_USER }}" --password-stdin 
          .devcontainer/cache/build-cache-image.sh "${BASE_IMAGE_ID}" "${BASE_IMAGE_ID}" "node" "." "true" "image"

          git config --global user.email "noreply@github.com"
          git config --global user.name "CI"
          git add .devcontainer/devcontainer.json
          git commit -am 'Automated devcontainer.json update' \
            && git push \
            || echo 'No updates to devcontainer.json'